theme: jekyll-theme-midnight
title: CV
name: Andrei Kitaitsev
email: andre.kit17@gmail.com
location: Oldebburg, Germany
photo: https://photos.google.com/u/1/photo/AF1QipP81d2cNRSuirz79JBsKqmRDwwGVLRsihlXMV-X
