theme: jekyll-theme-minimal
title: CV
name: Andrei Kitaitsev
email: andre.kit17@gmail.com
location: Berlin, Germany
photo: https://photos.google.com/u/1/photo/AF1QipP81d2cNRSuirz79JBsKqmRDwwGVLRsihlXMV-X
resume_social_links:
  resume_github_url: https://github.com/andreikitaitsev
  resume_linkedin_url: www.linkedin.com/in/andrei-kitaitsev-b21a32208
  resume_facebook_url: https://www.facebook.com/profile.php?id=100005166762332
resume_theme: default

resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

resume_looking_for_work:        "yes"
resume_avatar:                  "true"
